# Generated by Django 3.1.4 on 2021-01-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='empty-slug', max_length=200, unique=True),
        ),
    ]
