# Generated by Django 3.1.4 on 2021-03-16 13:07

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210314_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='first_img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='second_img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='third_img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.path_and_rename),
        ),
    ]
