# Generated by Django 3.1.4 on 2021-03-16 14:00

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210316_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=14, validators=[blog.models.validate_mobile]),
        ),
    ]
