# Generated by Django 3.1.4 on 2021-03-16 14:07

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210316_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile should start with country code followed by mobile number ex: +918724567890', max_length=14, validators=[blog.models.validate_mobile]),
        ),
    ]
