# Generated by Django 3.1.4 on 2021-03-16 14:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210316_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='xyz@xyz.com', max_length=254, validators=[blog.models.validate_email]),
        ),
    ]
